-- Read the docs: https://www.lunarvim.org/docs/configuration
-- Example configs: https://github.com/LunarVim/starter.lvim
-- Video Tutorials: https://www.youtube.com/watch?v=sFA9kX-Ud_c&list=PLhoH5vyxr6QqGu0i7tt_XoVK9v-KvZ3m6
-- Forum: https://www.reddit.com/r/lunarvim/
-- Discord: https://discord.com/invite/Xb9B4Ny
--
--
reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.lsp"
reload "user.clangd"
-- reload "user.smoothie"
-- reload "user.harpoon"
-- reload "user.autocommands"
-- reload "user.webdev-icons"
-- reload "user.cybu"
-- reload "user.neotest"
-- reload "user.surround"
-- reload "user.bookmark"
-- reload "user.todo-comments"
-- reload "user.jaq"
-- reload "user.fidget"
-- reload "user.lab"
-- reload "user.git"
-- reload "user.zen-mode"
-- reload "user.inlay-hints"
-- reload "user.telescope"
-- reload "user.bqf"
-- reload "user.dial"
-- reload "user.numb"
-- reload "user.treesitter"
-- reload "user.neogit"
-- reload "user.colorizer"
-- reload "user.lualine"
-- reload "user.tabnine"
-- reload "user.copilot"
-- -- reload "user.chatgpt"
-- reload "user.whichkey"
-- reload "user.neoai"
-- reload "user.cmp"
-- reload "user.nvimtree"
-- reload "nostr"
-- reload "user.astro-tools"
-- reload "user.matchup"
-- reload "user.modicator"

